name: 'Setup HHVM Action'
author: azjezz
description: 'setup HHVM with ease.'
branding:
  color: 'yellow'
  icon: 'layers'

input:
  version:
    description: 'HHVM version'
    default: 'stable'
    required: true

runs:
  using: 'composite'
  steps:
    - name: "installing hhvm"
      shell: bash
      run: |
        if [ "$RUNNER_OS" === "Linux" ]; then
          set -ex
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y software-properties-common apt-transport-https
          sudo apt-key add hhvm.gpg
          if [ "${{inputs.version}}" = 'nightly' ]; then
            sudo add-apt-repository https://dl.hhvm.com/ubuntu
            sudo apt-get install -y hhvm-nightly
          elif [ "${{inputs.version}}" = 'latest' ]; then
            sudo add-apt-repository https://dl.hhvm.com/ubuntu
            sudo apt-get install -y hhvm
          else
            DISTRO=$(lsb_release --codename --short)
            sudo add-apt-repository \
              "deb https://dl.hhvm.com/ubuntu ${DISTRO}-${{inputs.version}} main"
            sudo apt-get install -y hhvm
          fi
        elif [ "$RUNNER_OS" === "macOS"]; then
          brew tap hhvm/hhvm
          if [ "${{inputs.version}}" = 'latest' ]; then
            brew install hhvm
          else
            brew install hhvm-${{inputs.version}}
          fi
        else
          echo "$RUNNER_OS is not currently supported"
          exit 1
        fi
