name: 'Setup HHVM Action'
author: azjezz
description: 'setup HHVM with ease.'
branding:
  color: 'yellow'
  icon: 'layers'

inputs:
  version:
    description: 'HHVM version to install'
    default: 'stable'
    required: true
  debug:
    description: 'Install debug build that is suitable for debuggers like gdb'
    default: false
    required: false

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: ${{ github.action_path }}/scripts/composer.sh

    - shell: bash
      run: |
        if [ "$RUNNER_OS" = "Linux" ]; then
          set -ex
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y software-properties-common apt-transport-https
          sudo apt-key add ${{ github.action_path }}/resources/hhvm.gpg
          if [ "${{inputs.version}}" = 'nightly' ]; then
            sudo add-apt-repository https://dl.hhvm.com/ubuntu
            if [ "${{inputs.debug}}" = "true" ]; then
              sudo apt-get install -y hhvm-nightly-dbg
            else
              sudo apt-get install -y hhvm-nightly
            fi
          elif [ "${{inputs.version}}" = 'latest' ]; then
            sudo add-apt-repository https://dl.hhvm.com/ubuntu
            if [ "${{inputs.debug}}" = "true" ]; then
              sudo apt-get install -y hhvm-dbg
            else
              sudo apt-get install -y hhvm
            fi
          else
            DISTRO=$(lsb_release --codename --short)
            sudo add-apt-repository \
              "deb https://dl.hhvm.com/ubuntu ${DISTRO}-${{inputs.version}} main"
            if [ "${{inputs.debug}}" = "true" ]; then
              sudo apt-get install -y hhvm-dbg
            else
              sudo apt-get install -y hhvm
            fi
          fi
        elif [ "$RUNNER_OS" = "macOS" ]; then
          brew tap hhvm/hhvm
          if [ "${{inputs.version}}" = 'latest' ]; then
            if [ "${{inputs.debug}}" = "true" ]; then
              echo "debug builds are not currently supported for MacOS."
              exit 1
            fi

            brew install hhvm
          else
            if [ "${{inputs.debug}}" = "true" ]; then
              echo "debug builds are not currently supported for MacOS."
              exit 1
            fi

            brew install hhvm-${{inputs.version}}
          fi
        else
          echo "$RUNNER_OS is not currently supported."
          exit 1
        fi
