on: ["push"]

jobs:
  example:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - { hhvm: "4.84",    os: "ubuntu-latest", debug: true, legacy: false  }
          - { hhvm: "latest",  os: "ubuntu-latest", debug: true, legacy: false  }
          - { hhvm: "nightly", os: "ubuntu-latest", debug: true, legacy: false  }

          - { hhvm: "4.84",    os: "ubuntu-latest", debug: false, legacy: false }
          - { hhvm: "latest",  os: "ubuntu-latest", debug: false, legacy: false }
          - { hhvm: "nightly", os: "ubuntu-latest", debug: false, legacy: false }

          - { hhvm: "4.84",    os: "macos-latest" , debug: false, legacy: false }
          - { hhvm: "latest",  os: "macos-latest" , debug: false, legacy: false }
          - { hhvm: "nightly", os: "macos-latest" , debug: false, legacy: false }

          - { hhvm: "lts-3.30", os: "ubuntu-latest", debug: false, legacy: true }
          - { hhvm: "lts-3.30", os: "ubuntu-latest", debug: true , legacy: true }

    steps:
      - name: "checkout"
        uses: "actions/checkout@v2"

      - name: "install hhvm"
        uses: "azjezz/setup-hhvm@v1"
        with:
          version: ${{ matrix.hhvm }}
          debug: ${{ matrix.debug }}

      - name: "inspect"
        run: |
          php --version
          composer --version
          hhvm --version
          hh_client --version

      - name: "running hack script"
        if: ${{ matrix.legacy == false }}
        run: "hhvm scripts/example.hack"
